/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.User;
import Backend.UserManager;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Iterator;



/**
 *
 * @author mrali
 */
public class SearchForFriends extends javax.swing.JFrame {

    private final User user;
    /**
     * Creates new form SearchForFriends
     */
    public SearchForFriends(User user) {
        this.user = user;
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Name/Username:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String search = jTextField1.getText().trim();

        if(search.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a name or username to search for", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        // Search for the user
        ArrayList<User> searchResults = UserManager.searchByName(search, user);
        Iterator<User> iterator = searchResults.iterator();
//        while (iterator.hasNext()) {
//            User u = iterator.next();
//            if (user.getFriendManagement().getBlockedUsers().contains(u) ||
//                    user.getFriendManagement().getSentRequests().contains(u) ||
//                    user.getFriendManagement().getReceivedRequests().contains(u)) {
//                iterator.remove();
//            }
//        }

        if(searchResults.isEmpty()){
            JOptionPane.showMessageDialog(null, "No users found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create a panel to hold the search results
        JPanel resultsPanel = new JPanel();
        resultsPanel.setLayout(new BoxLayout(resultsPanel, BoxLayout.Y_AXIS));

        // Display the search results
        for (User selected : searchResults) {

            JPanel userPanel = new JPanel();
            userPanel.setLayout(new BoxLayout(userPanel, BoxLayout.X_AXIS));
            JLabel nameLabel = new JLabel(selected.getName() + " - " + selected.getUsername());
            userPanel.add(nameLabel);
            userPanel.add(Box.createHorizontalStrut(10)); // Add some space between the label and button
            if (user.getFriendManagement().isFriend(selected)) {
                JButton removeButton = new JButton("Remove Friend");
                removeButton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        user.getFriendManagement().removeFriend(selected);
                        JOptionPane.showMessageDialog(null, selected.getName()+" removed");
                        removeButton.setEnabled(false);
                        removeButton.setText("Removed");
                    }
                });

                userPanel.add(removeButton);
//                resultsPanel.add(userPanel);
//                resultsPanel.add(Box.createVerticalStrut(10)); // Add some space between user panels
            }

            if(!user.getFriendManagement().getBlockedUsers().contains(selected)){
                JButton blockButton = new JButton("Block User");
                blockButton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        user.getFriendManagement().blockUser(selected);
                        JOptionPane.showMessageDialog(null, selected.getName()+" blocked");
                        blockButton.setEnabled(false);
                        blockButton.setText("Blocked");
                    }
                });
                userPanel.add(blockButton);
            }
            else {
                JButton unblockButton = new JButton("Unblock User");
                unblockButton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        user.getFriendManagement().unblockUser(selected);
                        JOptionPane.showMessageDialog(null, selected.getName()+" unblocked");
                        unblockButton.setEnabled(false);
                        unblockButton.setText("Unblocked");
                    }
                });
                userPanel.add(unblockButton);
            }

            JButton viewProfileButton = new JButton("View Profile");
            viewProfileButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    new FriendProfile(selected).setVisible(true);
                }
            });
            userPanel.add(viewProfileButton);

            if(!user.getFriendManagement().isFriend(selected) && !user.getFriendManagement().getSentRequests().contains(selected) && !user.getFriendManagement().getReceivedRequests().contains(selected) && !user.getFriendManagement().getBlockedUsers().contains(selected)){
                JButton addButton = new JButton("Add Friend");
                addButton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        user.sendFriendRequest(selected);
                        JOptionPane.showMessageDialog(null, "Friend request sent to " + selected.getName());
                        addButton.setEnabled(false);
                        addButton.setText("Pending");
                    }
                });
//                userPanel.add(nameLabel);
//                userPanel.add(Box.createHorizontalStrut(10)); // Add some space between the label and button
                userPanel.add(addButton);

//                resultsPanel.add(userPanel);
//                resultsPanel.add(Box.createVerticalStrut(10)); // Add some space between user panels
            }
            resultsPanel.add(userPanel);
            resultsPanel.add(Box.createVerticalStrut(10)); // Add some space between user panels
        }

        jScrollPane1.setViewportView(resultsPanel);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
